#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Provisions the Azure side of ticket 14, once, by hand (ADR-0010): the
# resource group, the Log Analytics workspace, the Container Apps environment
# and app, the first image on GHCR made public, the Entra app registration
# GitHub Actions signs in as through OIDC, the repository variables the
# deploy job reads, and a cost budget. Every Azure call is the Azure CLI's,
# so the commands below are the record of what exists. Re-runnable: values
# are remembered in .env.azure (gitignored, no secret in it); the
# environment, the app, the Entra app, its role and its credential are
# skipped when they exist, and the rest is safe to repeat (az create on an
# existing group or workspace changes nothing; stage 5 pushes :bootstrap
# again).
#
#   bash scripts/provision-azure.sh        # from the repo root, in Git Bash
#
# Needs the Azure CLI (winget install -e --id Microsoft.AzureCLI), Docker
# Desktop running, and gh signed in. The Anthropic key is typed hidden, goes
# into a Container Apps secret through a private temp file, and is never
# written to .env.azure, a command line or GitHub.

cd "$(dirname "$0")/.."
ENV_FILE=.env.azure
# Git Bash would otherwise rewrite Azure resource ids (/subscriptions/...)
# into Windows paths.
export MSYS_NO_PATHCONV=1

# az on Windows ends its output lines with CR; strip it from captured values.
azq() { az "$@" | tr -d '\r'; }

# az is a Windows program under Git Bash, and MSYS_NO_PATHCONV stops a /tmp
# path being translated for it, so temp files are handed over in Windows form.
winpath() {
  if command -v cygpath >/dev/null 2>&1; then cygpath -m "$1"; else printf '%s' "$1"; fi
}

# ask_default KEY "Prompt" DEFAULT: ask (Enter keeps a remembered value),
# fall back to DEFAULT when nothing is remembered, and remember the result.
ask_default() {
  local key="$1" prompt="$2" default="$3"
  ask "$key" "$prompt [$default]"
  [[ -n "${!key}" ]] || printf -v "$key" '%s' "$default"
  write_env "$key" "${!key}"
}

need() {
  command -v "$1" >/dev/null 2>&1 || { warn "$1 not found: $2"; exit 1; }
}

TOTAL_STAGES=12

banner "cv-reformatter: Azure Container Apps, deployed through OIDC"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Tools and Azure sign-in"
need az "install it with: winget install -e --id Microsoft.AzureCLI (then reopen Git Bash)"
need docker "install Docker Desktop"
need gh "install the GitHub CLI"
docker info >/dev/null 2>&1 || { warn "Docker is not running: start Docker Desktop"; exit 1; }
gh auth status >/dev/null 2>&1 || { warn "gh is not signed in: run gh auth login"; exit 1; }
say "az, docker and gh are present."
if az account show >/dev/null 2>&1; then
  note "Already signed in to Azure as $(azq account show --query user.name -o tsv)."
else
  step "A browser opens for the Azure sign-in; pick your personal account."
  note "(If a Windows sign-in popup appears instead and fails silently, stop and run"
  note " az config set core.enable_broker_on_windows=false, then re-run the wizard.)"
  pause "Press Enter to run az login"
  az login --output none
fi
az account list --query "[].{name:name, id:id, default:isDefault}" --output table
ask_default AZURE_SUBSCRIPTION_ID "Subscription to use (name or id)" "$(azq account show --query id -o tsv)"
az account set --subscription "$AZURE_SUBSCRIPTION_ID"
# A name was accepted above; from here on (and in GitHub) it is the id.
AZURE_SUBSCRIPTION_ID=$(azq account show --query id -o tsv)
write_env AZURE_SUBSCRIPTION_ID "$AZURE_SUBSCRIPTION_ID"
note "Using $(azq account show --query name -o tsv) ($AZURE_SUBSCRIPTION_ID)."
AZURE_TENANT_ID=$(azq account show --query tenantId -o tsv)
write_env AZURE_TENANT_ID "$AZURE_TENANT_ID"
say "Registering the resource providers Container Apps needs (a minute or two the first time)."
az provider register --namespace Microsoft.App --wait
az provider register --namespace Microsoft.OperationalInsights --wait
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Names and region"
say "Enter keeps the default shown in brackets."
ask_default AZURE_LOCATION "Region" northeurope
ask_default AZURE_RESOURCE_GROUP "Resource group" cvr-rg
ask_default LOG_WORKSPACE "Log Analytics workspace" cvr-log
ask_default CONTAINERAPPS_ENV "Container Apps environment" cvr-cae
ask_default AZURE_CONTAINER_APP "Container app (its name is in the public URL)" cvr-ca
ask_default ENTRA_APP "Entra app registration GitHub Actions signs in as" cvr-github-deploy
ask_default GITHUB_REPO "GitHub repository (owner/name)" "$(gh repo view --json nameWithOwner -q .nameWithOwner)"
IMAGE="ghcr.io/${GITHUB_REPO,,}"
write_env IMAGE "$IMAGE"
FED_SUBJECT="repo:$GITHUB_REPO:ref:refs/heads/main"
write_env FED_SUBJECT "$FED_SUBJECT"
note "Image: $IMAGE    OIDC subject: $FED_SUBJECT"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Resource group and Log Analytics workspace"
say "Creates (or confirms) $AZURE_RESOURCE_GROUP and $LOG_WORKSPACE in $AZURE_LOCATION."
note "Log Analytics bills ingestion past its free allowance; this app logs a few KB a request."
confirm "Create them?" || { warn "stopped before creating anything"; exit 1; }
az group create --name "$AZURE_RESOURCE_GROUP" --location "$AZURE_LOCATION" --output none
az monitor log-analytics workspace create --resource-group "$AZURE_RESOURCE_GROUP" \
  --workspace-name "$LOG_WORKSPACE" --location "$AZURE_LOCATION" --retention-time 30 --output none
LOG_WORKSPACE_ID=$(azq monitor log-analytics workspace show --resource-group "$AZURE_RESOURCE_GROUP" \
  --workspace-name "$LOG_WORKSPACE" --query customerId -o tsv)
write_env LOG_WORKSPACE_ID "$LOG_WORKSPACE_ID"
say "Done. Workspace (customer) id: $LOG_WORKSPACE_ID"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Container Apps environment"
if az containerapp env show --name "$CONTAINERAPPS_ENV" --resource-group "$AZURE_RESOURCE_GROUP" >/dev/null 2>&1; then
  say "$CONTAINERAPPS_ENV already exists; skipping."
else
  say "Creates $CONTAINERAPPS_ENV: consumption only (no workload profiles), logs to $LOG_WORKSPACE."
  note "Takes a few minutes."
  confirm "Create it?" || { warn "stopped"; exit 1; }
  log_key=$(azq monitor log-analytics workspace get-shared-keys --resource-group "$AZURE_RESOURCE_GROUP" \
    --workspace-name "$LOG_WORKSPACE" --query primarySharedKey -o tsv)
  az containerapp env create --name "$CONTAINERAPPS_ENV" --resource-group "$AZURE_RESOURCE_GROUP" \
    --location "$AZURE_LOCATION" --enable-workload-profiles false \
    --logs-destination log-analytics --logs-workspace-id "$LOG_WORKSPACE_ID" \
    --logs-workspace-key "$log_key" --output none
  unset log_key
  say "Done."
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "First image on GHCR"
say "Container Apps pulls with no registry secret, so the package must exist and"
say "be public before the app is created. This builds the image here and pushes"
say "$IMAGE:bootstrap; the deploy job replaces it on the first merge to main."
step "gh needs the write:packages scope: a browser may open for a one-time code."
pause "Press Enter to refresh gh's scopes"
gh auth refresh --hostname github.com --scopes write:packages
gh auth token | docker login ghcr.io --username "$(gh api user --jq .login)" --password-stdin
docker build --label "org.opencontainers.image.source=https://github.com/$GITHUB_REPO" \
  --tag "$IMAGE:bootstrap" .
docker push "$IMAGE:bootstrap"
docker logout ghcr.io
say "Pushed, and docker is logged out of ghcr.io again."
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "GHCR package: public, and writable by the repo's Actions"
OWNER=${GITHUB_REPO%%/*}
PACKAGE=${GITHUB_REPO##*/}
open_url "https://github.com/users/$OWNER/packages/container/$PACKAGE/settings"
step "Danger Zone → Change visibility → Public → type '$PACKAGE' → confirm."
step "Manage Actions access → Add repository → $PACKAGE → role Write."
note "  (If $PACKAGE is already listed there, make sure its role is Write.)"
warn "Public means anyone can pull the image; ticket 12's checks keep secrets out of it."
pause "Press Enter once both are saved"
say "Checking an anonymous pull, and repeating ticket 12's inspection on the pushed image."
docker image rm "$IMAGE:bootstrap" >/dev/null 2>&1 || true
IMAGE="$IMAGE:bootstrap" PULL=1 sh scripts/check-image.sh
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "The container app"
if az containerapp show --name "$AZURE_CONTAINER_APP" --resource-group "$AZURE_RESOURCE_GROUP" >/dev/null 2>&1; then
  say "$AZURE_CONTAINER_APP already exists; skipping. To rotate its key, see"
  note "  docs/development.md, Deployment (read hidden, never typed into the history)."
else
  say "Creates $AZURE_CONTAINER_APP on $IMAGE:bootstrap: external ingress on 8000,"
  say "0 to 1 replicas, liveness and readiness probes on /health, 0.5 vCPU and 1 GiB,"
  say "and the Anthropic key as the Container Apps secret anthropic-api-key, which"
  say "the container reads as ANTHROPIC_API_KEY."
  open_url "https://console.anthropic.com/settings/keys"
  step "Create a key for this deployment (e.g. cvr-container-app) and copy it."
  ask_secret ANTHROPIC_API_KEY "Paste the key (hidden):"
  [[ -n "$ANTHROPIC_API_KEY" ]] || { warn "no key entered"; exit 1; }
  confirm "Create the app?" || { warn "stopped"; exit 1; }
  # The app is PUT to the ARM API as JSON with az rest, not through
  # `az containerapp create --yaml`: the CLI re-serialises a YAML spec through
  # its SDK model and sends every unset field as null, which ARM rejects ("The
  # JSON value could not be converted to System.Boolean"). The flag-based
  # create would put the key on the command line. Here the spec holds the
  # key, so the key never appears on a command line; the file is deleted as
  # soon as az has read it, and by the trap if the wizard is interrupted.
  # (chmod is best effort: on NTFS the user's temp directory is what keeps it
  # private.)
  env_id=$(azq containerapp env show --name "$CONTAINERAPPS_ENV" --resource-group "$AZURE_RESOURCE_GROUP" --query id -o tsv)
  app_uri="https://management.azure.com/subscriptions/$AZURE_SUBSCRIPTION_ID/resourceGroups/$AZURE_RESOURCE_GROUP/providers/Microsoft.App/containerApps/$AZURE_CONTAINER_APP?api-version=2024-03-01"
  spec=$(mktemp)
  trap 'rm -f "$spec"' EXIT
  chmod 600 "$spec"
  cat > "$spec" <<JSON
{
  "location": "$AZURE_LOCATION",
  "properties": {
    "environmentId": "$env_id",
    "configuration": {
      "activeRevisionsMode": "Single",
      "ingress": {"external": true, "targetPort": 8000, "transport": "auto"},
      "secrets": [{"name": "anthropic-api-key", "value": "$ANTHROPIC_API_KEY"}]
    },
    "template": {
      "containers": [{
        "name": "cvr",
        "image": "$IMAGE:bootstrap",
        "resources": {"cpu": 0.5, "memory": "1Gi"},
        "env": [{"name": "ANTHROPIC_API_KEY", "secretRef": "anthropic-api-key"}],
        "probes": [
          {"type": "Liveness", "httpGet": {"path": "/health", "port": 8000},
           "initialDelaySeconds": 5, "periodSeconds": 30},
          {"type": "Readiness", "httpGet": {"path": "/health", "port": 8000},
           "initialDelaySeconds": 5, "periodSeconds": 10}
        ]
      }],
      "scale": {"minReplicas": 0, "maxReplicas": 1}
    }
  }
}
JSON
  created=0
  # A body read from a file gets no Content-Type of its own; ARM requires one.
  az rest --method PUT --uri "$app_uri" --headers "Content-Type=application/json" \
    --body "@$(winpath "$spec")" --output none && created=1
  rm -f "$spec"
  trap - EXIT
  unset ANTHROPIC_API_KEY
  [[ "$created" == 1 ]] || { warn "create failed; the spec file is deleted"; exit 1; }
  say "Accepted; the spec file that held the key is deleted. Waiting for provisioning."
  for _ in $(seq 60); do
    state=$(azq containerapp show --name "$AZURE_CONTAINER_APP" --resource-group "$AZURE_RESOURCE_GROUP" \
      --query properties.provisioningState -o tsv)
    [[ "$state" == Succeeded || "$state" == Failed ]] && break
    sleep 5
  done
  [[ "$state" == Succeeded ]] || { warn "provisioning ended as '$state'; see the app in the portal"; exit 1; }
  say "Done: $AZURE_CONTAINER_APP is provisioned."
fi
APP_URL="https://$(azq containerapp show --name "$AZURE_CONTAINER_APP" --resource-group "$AZURE_RESOURCE_GROUP" \
  --query properties.configuration.ingress.fqdn -o tsv)"
write_env APP_URL "$APP_URL"
note "URL: $APP_URL"
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Smoke test the live app"
say "Wakes the app from zero (timing the cold start), posts one golden-set"
say "document and checks for a .docx with X-Run-Id. Calls the model once (cents)."
if confirm "Run it?"; then
  # The smoke script relies on Git Bash's path translation for curl's temp
  # files, which this wizard's MSYS_NO_PATHCONV would switch off.
  env -u MSYS_NO_PATHCONV sh scripts/smoke-deploy.sh "$APP_URL" || warn "the smoke test failed; see above"
fi
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Entra app registration and the OIDC federated credential"
say "Creates $ENTRA_APP (the identity the deploy job signs in as), its service"
say "principal, Contributor on $AZURE_RESOURCE_GROUP only, and a federated"
say "credential trusting GitHub's tokens for exactly: $FED_SUBJECT"
confirm "Create them?" || { warn "stopped"; exit 1; }
AZURE_CLIENT_ID=$(azq ad app list --display-name "$ENTRA_APP" --query "[0].appId" -o tsv)
if [[ -z "$AZURE_CLIENT_ID" ]]; then
  AZURE_CLIENT_ID=$(azq ad app create --display-name "$ENTRA_APP" --query appId -o tsv)
fi
write_env AZURE_CLIENT_ID "$AZURE_CLIENT_ID"
az ad sp show --id "$AZURE_CLIENT_ID" >/dev/null 2>&1 || az ad sp create --id "$AZURE_CLIENT_ID" --output none
sp_object_id=$(azq ad sp show --id "$AZURE_CLIENT_ID" --query id -o tsv)
rg_id=$(azq group show --name "$AZURE_RESOURCE_GROUP" --query id -o tsv)
assigned=$(azq role assignment list --assignee "$sp_object_id" --scope "$rg_id" --role Contributor --query 'length(@)' -o tsv)
if [[ "$assigned" == 0 ]]; then
  az role assignment create --assignee-object-id "$sp_object_id" --assignee-principal-type ServicePrincipal \
    --role Contributor --scope "$rg_id" --output none
fi
existing=$(azq ad app federated-credential list --id "$AZURE_CLIENT_ID" --query "[?name=='github-main'].name" -o tsv)
if [[ -z "$existing" ]]; then
  cred=$(mktemp)
  cat > "$cred" <<JSON
{
  "name": "github-main",
  "issuer": "https://token.actions.githubusercontent.com",
  "subject": "$FED_SUBJECT",
  "description": "GitHub Actions deploy job, push to main only",
  "audiences": ["api://AzureADTokenExchange"]
}
JSON
  az ad app federated-credential create --id "$AZURE_CLIENT_ID" --parameters "$(winpath "$cred")" --output none
  rm -f "$cred"
fi
az ad app federated-credential list --id "$AZURE_CLIENT_ID" --query "[].{name:name, subject:subject}" --output table
say "Client id: $AZURE_CLIENT_ID. No client secret was created."
pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "GitHub repository variables (not secrets)"
say "The deploy job logs in with these. They are identifiers, not credentials:"
say "without a token from this repo's main branch they open nothing."
set_var AZURE_CLIENT_ID "$AZURE_CLIENT_ID"
set_var AZURE_TENANT_ID "$AZURE_TENANT_ID"
set_var AZURE_SUBSCRIPTION_ID "$AZURE_SUBSCRIPTION_ID"
set_var AZURE_RESOURCE_GROUP "$AZURE_RESOURCE_GROUP"
set_var AZURE_CONTAINER_APP "$AZURE_CONTAINER_APP"
say "The repository's secrets (expect ANTHROPIC_API_KEY alone, nothing Azure):"
gh secret list
pause

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Cost budget"
say "The target is the free monthly grant. A budget alert is the tripwire; if it"
say "ever fires, kill whatever costs money: az group delete -n $AZURE_RESOURCE_GROUP"
open_url "https://portal.azure.com/#view/Microsoft_Azure_CostManagement/Menu/~/budgets"
step "If the link lands elsewhere: search the portal for 'Budgets' → Cost Management | Budgets."
step "Scope: your subscription. + Add → name cvr-budget, reset Monthly, amount e.g. 5."
step "Alert conditions: Actual 50% and 100%, Forecasted 100%; your email → Create."
ask_default BUDGET_AMOUNT "Monthly amount you set (subscription currency)" 5
pause

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Record for ADR-0010"
say "Paste this into the ticket 14 PR and check ADR-0010's table matches:"
printf '\n'
note "  subscription      $AZURE_SUBSCRIPTION_ID"
note "  tenant            $AZURE_TENANT_ID"
note "  region            $AZURE_LOCATION"
note "  resource group    $AZURE_RESOURCE_GROUP"
note "  log analytics     $LOG_WORKSPACE ($LOG_WORKSPACE_ID)"
note "  environment       $CONTAINERAPPS_ENV"
note "  container app     $AZURE_CONTAINER_APP  $APP_URL"
note "  image             $IMAGE (public)"
note "  entra app         $ENTRA_APP (client id $AZURE_CLIENT_ID)"
note "  oidc subject      $FED_SUBJECT"
note "  budget            $BUDGET_AMOUNT a month"
printf '\n'
say "Next: merge to main; the deploy job moves the app from :bootstrap to the commit's image."
pause "Press Enter to finish"

finish
